name: xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  dio: ^5.4.1
  flutter_screenutil: ^5.9.0
  flutter_swiper_view: ^1.1.8
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: ityingFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/2.0X/xiaomiBanner.png
    - assets/images/3.0X/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/2.0X/xiaomiBanner2.png
    - assets/images/3.0X/xiaomiBanner2.png
    - assets/images/hot_search.png
    - assets/images/2.0X/hot_search.png
    - assets/images/3.0X/hot_search.png
